name: Deploy to WP Engine
on:
  push:
    branches:
      - wpengine/dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - name: Install PHP dependencies
        run: composer install
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: pichardodev
          # Deploy Options
          REMOTE_PATH: "wp-content/themes/allanpichardo/"
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete --exclude=".*"
          CACHE_CLEAR: TRUE
